version: "1"
rules:
  - base: swiftwasm
    upstream: swift/master
    mergeMethod: merge
  - base: swift/master
    upstream: apple:swift/master
    mergeMethod: hardreset
  - base: swift/release/5.3
    upstream: apple:swift/release/5.3
    mergeMethod: hardreset
  - base: swiftwasm-release/5.3
    upstream: swift/release/5.3
    mergeMethod: merge
label: ":arrow_heading_down: Upstream Tracking"
